import type { ArticleMeta } from "./types";
import { transcriptionCyrilDion } from "@/data/articles/transcriptions/cyril-dion";
import { transcriptionLudovicDujardin } from "@/data/articles/transcriptions/ludovic-dujardin";
import { transcriptionNoemieLenoir } from "@/data/articles/transcriptions/noemie-lenoir";

export const articles: ArticleMeta[] = [
  // temporarily commented until read by experts
  // {
  //   type: "internal",
  //   slug: "stress-avant-un-examen",
  //   title: "Stress avant un examen : comment mieux le gérer ?",
  //   intro:
  //     "Mains moites, ventre noué, cœur qui s’accélère, pensées qui tournent en boucle…<br>Le stress avant un examen est une expérience que beaucoup d’étudiant·es connaissent.",
  //   author: "Vikie Ache",
  //   publishedAt: "2026-07-20",
  //   markdownFile: "stress-avant-un-examen.md",
  //   heroImage: "/articles/stress-avant-un-examen/hero.jpg",
  //   heroCredits:
  //     "Source : Adobe Stock<br>Média complètement généré par une IA et vérifié par un agent.",
  //   readingTime: 4,
  //   mainFeelingSlug: "anxiety",
  // },
  // {
  //   type: "internal",
  //   slug: "le-blues-du-dimanche-soir",
  //   title: "Le blues du dimanche soir : pourquoi cette angoisse revient chaque semaine ?",
  //   intro:
  //     "Le week-end touche à sa fin, la nuit tombe, et une boule au ventre commence à apparaître.<br>Tu regardes l’heure, tu penses au réveil du lundi matin, aux cours, aux mails, aux transports, aux responsabilités qui reviennent… et l’angoisse monte progressivement.",
  //   author: "Vickie Ache",
  //   publishedAt: "2026-07-20",
  //   markdownFile: "le-blues-du-dimanche-soir.md",
  //   heroImage: "/articles/le-blues-du-dimanche-soir/hero.jpg",
  //   heroCredits:
  //     "Source : Adobe Stock<br>Média complètement généré par une IA et vérifié par un agent.",
  //   readingTime: 5,
  //   mainFeelingSlug: "anxiety",
  // },
  {
    type: "podcast",
    slug: "podcast-cyril-dion",
    title: "Anxiété, crise environnementale : comment garder espoir ? Avec Cyril Dion",
    publishedAt: "2025-11-19",
    markdownFile: "cyril-dion.md",
    heroImage: "/articles/podcast/cyril-dion.jpg",
    mainFeelingSlug: "anxiety",
    podcastUrl: "https://embed.acast.com/$/65cb7c6311e3e5001505d3e6/cyril-dion-anxiete-crise-environnementale-comment-garder-esp?",
    transcription: transcriptionCyrilDion
  },
  {
    type: "podcast",
    slug: "podcast-ludovic-dujardin",
    title: "Et si s’arrêter, c’était avancer ? avec Ludovic Dujardin, fondateur de Petit Bambou",
    publishedAt: "2025-04-09",
    markdownFile: "ludovic-dujardin.md",
    heroImage: "/articles/podcast/ludovic-dujardin.jpg",
    mainFeelingSlug: "fatigue",
    podcastUrl: "https://embed.acast.com/$/65cb7c6311e3e5001505d3e6/et-si-sarreter-cetait-avancer?",
    transcription: transcriptionLudovicDujardin
  },
  {
    type: "podcast",
    slug: "podcast-noemie-lenoir",
    title: "Alcool, dépression : la descente aux enfers. Avec Noémie Lenoir. ",
    publishedAt: "2025-10-22",
    markdownFile: "noemie-lenoir.md",
    heroImage: "/articles/podcast/noemie-lenoir.jpg",
    mainFeelingSlug: "drugs",
    podcastUrl: "https://embed.acast.com/$/65cb7c6311e3e5001505d3e6/noemie-lenoir-alcool-depression-la-descente-aux-enfers?",
    transcription: transcriptionNoemieLenoir
  },
  {
    type: "external",
    slug: "quand-le-sommeil-s-en-mele",
    url: "https://www.psycom.org/sinformer/la-sante-mentale/quand-le-sommeil-sen-mele/",
    intro:
      "La qualité de nos nuits peut favoriser ou au contraire fragiliser notre santé mentale. Voici des pistes pour l'améliorer.",
    readingTime: 4,
    title: "Psycom - Quand le sommeil s'en mêle",
    mainFeelingSlug: "fatigue",
    heroImage: "/articles/quand-le-sommeil-s-en-mele/hero.jpg",
  },
  {
    type: "external",
    slug: "mieux-vivre-avec-un-trouble-anxieux",
    url: "https://www.santepsyjeunes.fr/media/pages/troubles-psychiques/trouble-anxieux-generalise/23472fbf89-1751032348/bat-trouble-anxieux_5.10.2023.pdf",
    intro: "",
    readingTime: 4,
    title: "Santé Psy Jeunes - Mieux vivre avec un trouble anxieux",
    mainFeelingSlug: "anxiety",
    heroImage: "/articles/mieux-vivre-avec-un-trouble-anxieux/hero.jpg",
  },
  {
    type: "external",
    slug: "troubles-anxieux-et-phobies",
    url: "https://www.psycom.org/sinformer/la-sante-mentale/les-troubles-psy/troubles-anxieux-et-phobies/#peur-anxiete-de-quoi-parle-t-on-6ab3a53c6a9ba",
    intro: "",
    readingTime: 4,
    title: "Psycom - Troubles anxieux et phobies",
    mainFeelingSlug: "anxiety",
    heroImage: "/articles/troubles-anxieux-et-phobies/hero.jpg",
  },
  {
    type: "external",
    slug: "comment-mieux-vivre-avec-nos-angoisses",
    url: "https://www.radiofrance.fr/franceinter/podcasts/grand-bien-vous-fasse/grand-bien-vous-fasse-du-lundi-04-novembre-2024-5814285",
    intro: "",
    readingTime: 4,
    title: "Radio France - Comment mieux vivre avec nos angoisses ?",
    mainFeelingSlug: "anxiety",
    heroImage: "/articles/comment-mieux-vivre-avec-nos-angoisses/hero.jpg",
  },
  {
    type: "external",
    slug: "mieux-comprendre-le-sommeil",
    url: "https://www.santepsyjeunes.fr/media/pages/brochures/sommeil/852026e224-1728398769/bat-sommeil-ado_2024.pdf",
    intro: "",
    readingTime: 4,
    title: "Santé Psy Jeunes - Mieux comprendre le sommeil à l’adolescence & chez le jeune adulte",
    mainFeelingSlug: "fatigue",
    heroImage: "/articles/mieux-comprendre-le-sommeil/hero.jpg",
  },
  {
    type: "external",
    slug: "sommeil-temps-moyen-sur",
    url: "https://www.santepubliquefrance.fr/index.php/sommeil/rapportsynthese/sommeil-temps-moyen-sur-24-heures-et-plainte-dinsomnie-barometre-de-sante-publique-france-resultats",
    intro: "",
    readingTime: 4,
    title:
      "Santé Publique France - Sommeil : temps moyen sur 24 heures et plainte d’insomnie (édition 2024)",
    mainFeelingSlug: "fatigue",
    heroImage: "/articles/sommeil-temps-moyen-sur/hero.jpg",
  },
  {
    type: "external",
    slug: "le-sommeil-et-ses-troubles",
    url: "https://reseau-morphee.fr/le-sommeil-et-ses-troubles-informations",
    intro: "",
    readingTime: 4,
    title: "Réseau Morphée - Le sommeil et ses troubles",
    mainFeelingSlug: "fatigue",
    heroImage: "/articles/le-sommeil-et-ses-troubles/hero.jpg",
  },
  {
    type: "external",
    slug: "asthenie",
    url: "https://www.ameli.fr/llle-et-vilaine/assure/sante/themes/asthenie-fatigue/bons-reflexes-cas-faut-consulter",
    intro: "",
    readingTime: 4,
    title: "Assurance maladie - Asthénie (fatigue) : que faire et quand consulter ?",
    mainFeelingSlug: "fatigue",
    heroImage: "/articles/asthenie/hero.jpg",
  },
  {
    type: "external",
    slug: "comprendre-les-addictions",
    url: "https://www.santepsyjeunes.fr/media/pages/brochures/mieux-comprendre-les-addictions/068a5da6a8-1776351896/lmp_brochures_addiction_bat-digital.pdf",
    intro: "",
    readingTime: 4,
    title: "Santé Psy Jeunes - Comprendre les addictions",
    mainFeelingSlug: "drugs",
    heroImage: "/articles/comprendre-les-addictions/hero.jpg",
  },
  {
    type: "external",
    slug: "drogues-info-service",
    url: "https://www.drogues-info-service.fr/",
    intro: "",
    readingTime: 4,
    title:
      "Drogues Info Service : service national d’aide à distance en matière de drogues et de dépendances",
    mainFeelingSlug: "drugs",
    heroImage: "/articles/drogues-info-service/hero.jpg",
  },
  {
    type: "external",
    slug: "les-trouves-addictifs",
    url: "https://www.psycom.org/sinformer/la-sante-mentale/les-troubles-psy/troubles-addictifs/",
    intro: "",
    readingTime: 4,
    title: "Psycom - Les trouves addictifs",
    mainFeelingSlug: "drugs",
    heroImage: "/articles/les-trouves-addictifs/hero.jpg",
  },
  {
    type: "external",
    slug: "la-solitude-des-jeunes",
    url: "https://www.psycom.org/actualites/revue-de-presse/solitude-les-jeunes-aussi/",
    intro: "",
    readingTime: 4,
    title: "Psycom - La solitude des jeunes",
    mainFeelingSlug: "solitude",
    heroImage: "/articles/la-solitude-des-jeunes/hero.jpg",
  },
  {
    type: "external",
    slug: "hyperconnectes-mais-seuls",
    url: "https://www.info.gouv.fr/actualite/hyperconnectes-mais-seuls-la-solitude-chez-les-jeunes",
    intro: "",
    readingTime: 4,
    title: "Info.gouv - Jeunes : hyperconnectés mais seuls",
    mainFeelingSlug: "solitude",
    heroImage: "/articles/hyperconnectes-mais-seuls/hero.jpg",
  },
  {
    type: "external",
    slug: "une-menace-cachee-pour",
    url: "https://www.who.int/fr/news-room/commentaries/detail/loneliness-and-isolation-the-hidden-threat-to-global-health-we-can-no-longer-ignore",
    intro: "",
    readingTime: 4,
    title: "OMS - Solitude et isolement : une menace cachée pour la santé mondiale",
    mainFeelingSlug: "solitude",
    heroImage: "/articles/une-menace-cachee-pour/hero.jpg",
  },
  {
    type: "external",
    slug: "deviens-benevole-avec-je-veux-aider",
    url: "https://www.etudiant.gouv.fr/fr/jeveuxaidergouvfr-la-plateforme-publique-du-benevolat-2342",
    intro: "",
    readingTime: 4,
    title: "Etudiant.gouv : Deviens bénévole avec Je Veux Aider",
    mainFeelingSlug: "solitude",
    heroImage: "/articles/deviens-benevole-avec-je-veux-aider/hero.jpg",
  },
];
