import { FEELING_ANXIETY } from "../feelings/anxiety";
import { FEELING_DRUGS } from "../feelings/drugs";
import { FEELING_FATIGUE } from "../feelings/fatigue";
import { FEELING_SOLITUDE } from "../feelings/solitude";
import type { ArticleMeta } from "./types";

export const articles: ArticleMeta[] = [
  {
    type: "internal",
    slug: "stress-avant-un-examen",
    title: "Stress avant un examen : comment mieux le gérer ?",
    intro:
      "Mains moites, ventre noué, cœur qui s’accélère, pensées qui tournent en boucle…<br>Le stress avant un examen est une expérience que beaucoup d’étudiant·es connaissent.",
    author: "Vikie Ache",
    publishedAt: "2026-07-20",
    markdownFile: "stress-avant-un-examen.md",
    heroImage: "/articles/stress-avant-un-examen/hero.jpg",
    heroCredits:
      "Source : Adobe Stock<br>Média complètement généré par une IA et vérifié par un agent.",
    readingTime: 4,
    mainFeeling: FEELING_ANXIETY,
  },
  {
    type: "internal",
    slug: "le-blues-du-dimanche-soir",
    title: "Le blues du dimanche soir : pourquoi cette angoisse revient chaque semaine ?",
    intro:
      "Le week-end touche à sa fin, la nuit tombe, et une boule au ventre commence à apparaître.<br>Tu regardes l’heure, tu penses au réveil du lundi matin, aux cours, aux mails, aux transports, aux responsabilités qui reviennent… et l’angoisse monte progressivement.",
    author: "Vickie Ache",
    publishedAt: "2026-07-20",
    markdownFile: "le-blues-du-dimanche-soir.md",
    heroImage: "/articles/le-blues-du-dimanche-soir/hero.jpg",
    heroCredits:
      "Source : Adobe Stock<br>Média complètement généré par une IA et vérifié par un agent.",
    readingTime: 5,
    mainFeeling: FEELING_ANXIETY,
  },
  {
    type: "external",
    slug: "quand-le-sommeil-s-en-mele",
    url: "https://www.psycom.org/sinformer/la-sante-mentale/quand-le-sommeil-sen-mele/",
    intro:
      "La qualité de nos nuits peut favoriser ou au contraire fragiliser notre santé mentale. Voici des pistes pour l'améliorer.",
    readingTime: 4,
    title: "Psycom - Quand le sommeil s'en mêle",
    mainFeeling: FEELING_FATIGUE,
    heroImage: "/articles/quand-le-sommeil-s-en-mele/hero.jpg",
  },
  {
    type: "external",
    slug: "mieux-vivre-avec-un-trouble-anxieux",
    url: "https://www.santepsyjeunes.fr/media/pages/troubles-psychiques/trouble-anxieux-generalise/23472fbf89-1751032348/bat-trouble-anxieux_5.10.2023.pdf",
    intro: "",
    readingTime: 4,
    title: "Santé Psy Jeunes - Mieux vivre avec un trouble anxieux",
    mainFeeling: FEELING_ANXIETY,
    heroImage: "/articles/mieux-vivre-avec-un-trouble-anxieux/hero.jpg",
  },
  {
    type: "external",
    slug: "troubles-anxieux-et-phobies",
    url: "https://www.psycom.org/sinformer/la-sante-mentale/les-troubles-psy/troubles-anxieux-et-phobies/#peur-anxiete-de-quoi-parle-t-on-6ab3a53c6a9ba",
    intro: "",
    readingTime: 4,
    title: "Psycom - Troubles anxieux et phobies",
    mainFeeling: FEELING_ANXIETY,
    heroImage: "/articles/troubles-anxieux-et-phobies/hero.jpg",
  },
  {
    type: "external",
    slug: "comment-mieux-vivre-avec-nos-angoisses",
    url: "https://www.radiofrance.fr/franceinter/podcasts/grand-bien-vous-fasse/grand-bien-vous-fasse-du-lundi-04-novembre-2024-5814285",
    intro: "",
    readingTime: 4,
    title: "Radio France - Comment mieux vivre avec nos angoisses ?",
    mainFeeling: FEELING_ANXIETY,
    heroImage: "/articles/comment-mieux-vivre-avec-nos-angoisses/hero.jpg",
  },
  {
    type: "external",
    slug: "mieux-comprendre-le-sommeil",
    url: "https://www.santepsyjeunes.fr/media/pages/brochures/sommeil/852026e224-1728398769/bat-sommeil-ado_2024.pdf",
    intro: "",
    readingTime: 4,
    title: "Santé Psy Jeunes - Mieux comprendre le sommeil à l’adolescence & chez le jeune adulte",
    mainFeeling: FEELING_FATIGUE,
    heroImage: "/articles/mieux-comprendre-le-sommeil/hero.jpg",
  },
  {
    type: "external",
    slug: "sommeil-temps-moyen-sur",
    url: "https://www.santepubliquefrance.fr/index.php/sommeil/rapportsynthese/sommeil-temps-moyen-sur-24-heures-et-plainte-dinsomnie-barometre-de-sante-publique-france-resultats",
    intro: "",
    readingTime: 4,
    title:
      "Santé Publique France - Sommeil : temps moyen sur 24 heures et plainte d’insomnie (édition 2024)",
    mainFeeling: FEELING_FATIGUE,
    heroImage: "/articles/sommeil-temps-moyen-sur/hero.jpg",
  },
  {
    type: "external",
    slug: "le-sommeil-et-ses-troubles",
    url: "https://reseau-morphee.fr/le-sommeil-et-ses-troubles-informations",
    intro: "",
    readingTime: 4,
    title: "Réseau Morphée - Le sommeil et ses troubles",
    mainFeeling: FEELING_FATIGUE,
    heroImage: "/articles/le-sommeil-et-ses-troubles/hero.jpg",
  },
  {
    type: "external",
    slug: "asthenie",
    url: "https://www.ameli.fr/llle-et-vilaine/assure/sante/themes/asthenie-fatigue/bons-reflexes-cas-faut-consulter",
    intro: "",
    readingTime: 4,
    title: "Assurance maladie - Asthénie (fatigue) : que faire et quand consulter ?",
    mainFeeling: FEELING_FATIGUE,
    heroImage: "/articles/asthenie/hero.jpg",
  },
  {
    type: "external",
    slug: "comprendre-les-addictions",
    url: "https://www.santepsyjeunes.fr/media/pages/brochures/mieux-comprendre-les-addictions/068a5da6a8-1776351896/lmp_brochures_addiction_bat-digital.pdf",
    intro: "",
    readingTime: 4,
    title: "Santé Psy Jeunes - Comprendre les addictions",
    mainFeeling: FEELING_DRUGS,
    heroImage: "/articles/comprendre-les-addictions/hero.jpg",
  },
  {
    type: "external",
    slug: "drogues-info-service",
    url: "https://www.drogues-info-service.fr/",
    intro: "",
    readingTime: 4,
    title:
      "Drogues Info Service : service national d’aide à distance en matière de drogues et de dépendances",
    mainFeeling: FEELING_DRUGS,
    heroImage: "/articles/drogues-info-service/hero.jpg",
  },
  {
    type: "external",
    slug: "les-trouves-addictifs",
    url: "https://www.psycom.org/sinformer/la-sante-mentale/les-troubles-psy/troubles-addictifs/",
    intro: "",
    readingTime: 4,
    title: "Psycom - Les trouves addictifs",
    mainFeeling: FEELING_DRUGS,
    heroImage: "/articles/les-trouves-addictifs/hero.jpg",
  },
  {
    type: "external",
    slug: "la-solitude-des-jeunes",
    url: "https://www.psycom.org/actualites/revue-de-presse/solitude-les-jeunes-aussi/",
    intro: "",
    readingTime: 4,
    title: "Psycom - La solitude des jeunes",
    mainFeeling: FEELING_SOLITUDE,
    heroImage: "/articles/la-solitude-des-jeunes/hero.jpg",
  },
  {
    type: "external",
    slug: "hyperconnectes-mais-seuls",
    url: "https://www.info.gouv.fr/actualite/hyperconnectes-mais-seuls-la-solitude-chez-les-jeunes",
    intro: "",
    readingTime: 4,
    title: "Info.gouv - Jeunes : hyperconnectés mais seuls",
    mainFeeling: FEELING_SOLITUDE,
    heroImage: "/articles/hyperconnectes-mais-seuls/hero.jpg",
  },
  {
    type: "external",
    slug: "une-menace-cachee-pour",
    url: "https://www.who.int/fr/news-room/commentaries/detail/loneliness-and-isolation-the-hidden-threat-to-global-health-we-can-no-longer-ignore",
    intro: "",
    readingTime: 4,
    title: "OMS - Solitude et isolement : une menace cachée pour la santé mondiale",
    mainFeeling: FEELING_SOLITUDE,
    heroImage: "/articles/une-menace-cachee-pour/hero.jpg",
  },
  {
    type: "external",
    slug: "deviens-benevole-avec-je-veux-aider",
    url: "https://www.etudiant.gouv.fr/fr/jeveuxaidergouvfr-la-plateforme-publique-du-benevolat-2342",
    intro: "",
    readingTime: 4,
    title: "Etudiant.gouv : Deviens bénévole avec Je Veux Aider",
    mainFeeling: FEELING_SOLITUDE,
    heroImage: "/articles/deviens-benevole-avec-je-veux-aider/hero.jpg",
  },
];
